// 由 quiz_data.py 自动生成
// 生成时间: 2026-04-25

// 格式: [品牌中文名, 品牌英文名, 集团简称(选项用), 集团内部名, 类型码]
// 类型码: f=时装与皮具, c=化妆品与香水, w=腕表与珠宝, g=眼镜, l=酒类, o=其他

const BRANDS = [
  ["Louis Vuitton路易威登", "Louis Vuitton", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Christian Dior迪奥", "Christian Dior", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Loro Piana诺悠翩雅", "Loro Piana", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Fendi芬迪", "Fendi", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Givenchy纪梵希", "Givenchy", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Celine思琳", "Celine", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Loewe罗意威", "Loewe", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Berluti伯尔鲁帝", "Berluti", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Barton Perreira", "", "LVMH 路威酩轩", "LVMH路威酩轩集团", "g"],
  ["Emilio Pucci璞琪", "Emilio Pucci", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Kenzo高田贤三", "Kenzo", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Marc Jacobs马克雅可布", "Marc Jacobs", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Moynat摩奈", "Moynat", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Patou巴度", "Patou", "LVMH 路威酩轩", "LVMH路威酩轩集团", "f"],
  ["Vuarnet", "", "LVMH 路威酩轩", "LVMH路威酩轩集团", "g"],
  ["Acqua di Parma帕尔马之水", "Acqua di Parma", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Benefit Cosmetics贝玲妃", "Benefit Cosmetics", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Bvlgari Parfums宝格丽香水", "Bvlgari Parfums", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Celine Parfums思琳香水", "Celine Parfums", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Christian Dior Parfums迪奥香水", "Christian Dior Parfums", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Cha Ling茶灵", "Cha Ling", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Fenty Beauty by Rihanna", "", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Fresh馥蕾诗", "Fresh", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Givenchy Parfums纪梵希香水", "Givenchy Parfums", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Guerlain法国娇兰", "Guerlain", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["KVD Beauty", "", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Kenzo Parfums", "", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Loewe Perfumes罗意威香水", "Loewe Perfumes", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Maison Francis Kurkdjian梵诗柯香", "Maison Francis Kurkdjian", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Make up for ever玫珂菲", "Make up for ever", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Ole Henriksen奥丽哈力逊", "Ole Henriksen", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Officine Universelle Buly普利 1803", "Officine Universelle Buly", "LVMH 路威酩轩", "LVMH路威酩轩集团", "c"],
  ["Daniel Roth丹尼尔罗斯", "Daniel Roth", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Gérald Genta尊达", "Gérald Genta", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Hublot宇舶", "Hublot", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["TAG Heuer泰格豪雅", "TAG Heuer", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Zenith真力时", "Zenith", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Bvlgari宝格丽", "Bvlgari", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Chaumet尚美巴黎", "Chaumet", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Fred斐登", "Fred", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Repossi雷波西", "Repossi", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["Tiffany & Co.蒂芙尼", "Tiffany & Co.", "LVMH 路威酩轩", "LVMH路威酩轩集团", "w"],
  ["DFS免税店", "DFS", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["Le Bon Marché乐蓬马歇百货", "Le Bon Marché", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["La Samaritaine莎玛丽丹百货", "La Samaritaine", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["24S.com 电商平台", "24S.com", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["Belmond贝梦德酒店", "Belmond", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["Cova（甜品）", "Cova", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["Cheval Blanc白马庄园", "Cheval Blanc", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
  ["Ardbeg雅伯", "Ardbeg", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Glenmorangie格兰杰", "Glenmorangie", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Hennessy轩尼诗", "Hennessy", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Woodinville伍丁维尔", "Woodinville", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Ao Yun敖云", "Ao Yun", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Bodega Numanthia弩曼希亚酒庄", "Bodega Numanthia", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Chateau Cheval Blanc白马酒庄", "Chateau Cheval Blanc", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Chateau D'yquem滴金酒庄", "Chateau D'yquem", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Colgin Cellars蔻金酒庄", "Colgin Cellars", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Cheval des Andes安第斯白马酒庄", "Cheval des Andes", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Cloudy Bay云雾之湾", "Cloudy Bay", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Domaine des Lambrays朗贝雷酒庄", "Domaine des Lambrays", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Joseph Phelps约瑟夫菲尔普斯", "Joseph Phelps", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Newton Vineyard纽顿酒庄", "Newton Vineyard", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Dom Pérignon唐培里侬", "Dom Pérignon", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Domaine Chandon夏桐", "Domaine Chandon", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Krug库克香槟", "Krug", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Mo.t & Chandon酩悦", "Mo.t & Chandon", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Mercier梅西埃", "Mercier", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Ruinart汇雅香槟", "Ruinart", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Veuve Clicquot凯歌香槟", "Veuve Clicquot", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Belvedere雪树伏特加", "Belvedere", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Eminente埃米南特朗姆酒", "Eminente", "LVMH 路威酩轩", "LVMH路威酩轩集团", "l"],
  ["Gucci古驰", "Gucci", "Kering 开云", "Kering开云集团", "f"],
  ["Saint Laurent圣罗兰", "Saint Laurent", "Kering 开云", "Kering开云集团", "f"],
  ["Bottega Veneta葆蝶家", "Bottega Veneta", "Kering 开云", "Kering开云集团", "f"],
  ["Balenciaga巴黎世家", "Balenciaga", "Kering 开云", "Kering开云集团", "f"],
  ["Alexander McQueen麦昆", "Alexander McQueen", "Kering 开云", "Kering开云集团", "f"],
  ["Brioni布里奥尼", "Brioni", "Kering 开云", "Kering开云集团", "f"],
  ["Boucheron宝诗龙", "Boucheron", "Kering 开云", "Kering开云集团", "w"],
  ["Pomellato宝曼兰朵", "Pomellato", "Kering 开云", "Kering开云集团", "w"],
  ["Qeelin麒麟", "Qeelin", "Kering 开云", "Kering开云集团", "w"],
  ["DoDo都都", "DoDo", "Kering 开云", "Kering开云集团", "w"],
  ["Ginori 1735", "", "Kering 开云", "Kering开云集团", "o"],
  ["Alexander McQueen麦昆眼镜", "Alexander McQueen", "Kering 开云", "Kering开云集团", "g"],
  ["ALAI.A阿莱亚眼镜", "ALAI.A", "Kering 开云", "Kering开云集团", "g"],
  ["Bottega Veneta葆蝶家眼镜", "Bottega Veneta", "Kering 开云", "Kering开云集团", "g"],
  ["Balenciaga巴黎世家眼镜", "Balenciaga", "Kering 开云", "Kering开云集团", "g"],
  ["Cartier卡地亚眼镜", "Cartier", "Kering 开云", "Kering开云集团", "g"],
  ["Chloé蔻依眼镜", "Chloé", "Kering 开云", "Kering开云集团", "g"],
  ["Dunhill登喜路眼镜", "Dunhill", "Kering 开云", "Kering开云集团", "g"],
  ["Gucci古驰眼镜", "Gucci", "Kering 开云", "Kering开云集团", "g"],
  ["Lindberg林德伯格", "Lindberg", "Kering 开云", "Kering开云集团", "g"],
  ["Montblanc万宝龙眼镜", "Montblanc", "Kering 开云", "Kering开云集团", "g"],
  ["Maui Jim茂宜晴", "Maui Jim", "Kering 开云", "Kering开云集团", "g"],
  ["Puma彪马眼镜", "Puma", "Kering 开云", "Kering开云集团", "g"],
  ["Saint Laurent圣罗兰眼镜", "Saint Laurent", "Kering 开云", "Kering开云集团", "g"],
  ["ZEAL Optics", "", "Kering 开云", "Kering开云集团", "g"],
  ["Purdey珀迪", "Purdey", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Delvaux德尔沃", "Delvaux", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Montblanc万宝龙", "Montblanc", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Dunhill登喜路", "Dunhill", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["ALAI.A阿莱亚", "ALAI.A", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Serapian塞拉皮安", "Serapian", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Gianvito Rossi吉安维托罗西", "Gianvito Rossi", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Chloé蔻依", "Chloé", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["G/FORE吉福", "G/FORE", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["Peter Millar彼得米拉", "Peter Millar", "Richemont 历峰", "Richemont历峰集团", "f"],
  ["A. Lange & S.hne朗格", "A. Lange & S.hne", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Baume & Mercier名士", "Baume & Mercier", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["IWC Schaffhausen万国表", "IWC Schaffhausen", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Jaeger – LeCoultre 积家", "Jaeger – LeCoultre", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Piaget伯爵", "Piaget", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Panerai沛纳海", "Panerai", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Roger Dubuis 罗杰杜彼", "Roger Dubuis", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Vacheron Constantin 江诗丹顿", "Vacheron Constantin", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Buccellati布契拉提", "Buccellati", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Cartier卡地亚", "Cartier", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Van Cleef & Arpels梵克雅宝", "Van Cleef & Arpels", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Vhernier 维尔尼尔", "Vhernier", "Richemont 历峰", "Richemont历峰集团", "w"],
  ["Darphin巴黎朵梵", "Darphin", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["ESTēE LAUDER雅诗兰黛", "ESTēE LAUDER", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["La Mer海蓝之谜", "La Mer", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Aramis雅男士", "Aramis", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Clinique倩碧", "Clinique", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Dr. Jart+蒂佳婷", "Dr. Jart+", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Glamglow格莱魅", "Glamglow", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Lab Series朗仕", "Lab Series", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Origins悦木之源", "Origins", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["The Ordinary 研度公式", "The Ordinary", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Bobbi Brown芭比波朗", "Bobbi Brown", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["M.A.C魅可", "M.A.C", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Tom Ford Beauty汤姆福德美妆", "Tom Ford Beauty", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Too Faced", "", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["AERIN雅芮", "AERIN", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Editions de Parfums Frederic Malle馥马尔香水出版社", "Editions de Parfums Frederic Malle", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Jo Malone祖马龙", "Jo Malone", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Kilian凯利安", "Kilian", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Le Labo勒莱柏", "Le Labo", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Aveda艾梵达", "Aveda", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Bumble and bumble.", "", "Estee Lauder 雅诗兰黛", "ESTēE LAUDER雅诗兰黛集团", "c"],
  ["Lancome兰蔻", "Lancome", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Yves Saint Laurent Beauté圣罗兰美妆", "Yves Saint Laurent Beauté", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Armani Beauty阿玛尼美妆", "Armani Beauty", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Valentino Beauty华伦天奴美妆", "Valentino Beauty", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["HR赫莲娜", "HR", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Miu Miu缪缪美妆", "Miu Miu", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Prada Beauty普拉达美妆", "Prada Beauty", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Kiehl's科颜氏", "Kiehl's", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Shu Uemura植村秀", "Shu Uemura", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Atelier Cologne法国欧珑", "Atelier Cologne", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Aesop伊索", "Aesop", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Azzaro阿莎罗", "Azzaro", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Biotherm碧欧泉", "Biotherm", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Carita凯芮黛", "Carita", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Cacharel卡夏尔", "Cacharel", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Diesel迪塞尔美妆", "Diesel", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["IT Cosmetics依科美", "IT Cosmetics", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Maison Margiela Fragrances梅森马吉拉香氛", "Maison Margiela Fragrances", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Mugler穆格勒", "Mugler", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Ralph Lauren Fragrances拉夫劳伦香氛", "Ralph Lauren Fragrances", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Takami高见", "Takami", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Urban Decay衰败城市", "Urban Decay", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Viktor&Rolf维果罗夫美妆", "Viktor&Rolf", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Yue Sai羽西", "Yue Sai", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Youth To The People", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["L'ORéAL PARIS巴黎欧莱雅", "L'ORéAL PARIS", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Dr.G蒂迩肌", "Dr.G", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Dark & Lovely", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Essie艾茜", "Essie", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Garnier卡尼尔", "Garnier", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Maybelline New York美宝莲纽约", "Maybelline New York", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Mixa", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["NYX Professional Makeup逆色", "NYX Professional Makeup", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Niely", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Thayers金缕梅", "Thayers", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Vogue", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["3CE三熹玉", "3CE", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Kérastase卡诗", "Kérastase", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["欧莱雅 PRO L'Oréal Professionnel Paris", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Biolage碧拉吉", "Biolage", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Matrix美奇丝", "Matrix", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Mizani", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Pureology", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Pulp Riot", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Redken丽得康", "Redken", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Shu Uemura Art of Hair 植村秀美发", "Shu Uemura Art of Hair", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["CeraVe适乐肤", "CeraVe", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["La Roche-Posay理肤泉", "La Roche-Posay", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["SkinCeuticals修丽可", "SkinCeuticals", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Skinbetter Science", "", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Vichy薇姿", "Vichy", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Alexander McQueen麦昆香水", "Alexander McQueen", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Bottega Veneta葆蝶家香水", "Bottega Veneta", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Balenciaga巴黎世家香水", "Balenciaga", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Creed恺芮得", "Creed", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Pomellato宝曼兰朵香水", "Pomellato", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Qeelin麒麟香水", "Qeelin", "LOreal 欧莱雅", "L’Oréal欧莱雅集团", "c"],
  ["Blancpain宝珀", "Blancpain", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Breguet宝玑", "Breguet", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Glashütte Original格拉苏蒂原创", "Glashütte Original", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Harry Winston海瑞温斯顿", "Harry Winston", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Jaquet Droz雅克德罗", "Jaquet Droz", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Omega欧米茄", "Omega", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Longines浪琴", "Longines", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Rado雷达表", "Rado", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Union Glashütte宇联", "Union Glashütte", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Balmain巴尔曼", "Balmain", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Certina雪铁纳", "Certina", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Hamilton汉密尔顿", "Hamilton", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Mido美度", "Mido", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Tissot天梭", "Tissot", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Calvin Klein卡尔文克莱恩", "Calvin Klein", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Flik Flak飞菲", "Flik Flak", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Swatch斯沃琪", "Swatch", "Swatch 斯沃琪", "Swatch斯沃琪集团", "w"],
  ["Amiri埃米尔", "Amiri", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Brave Kid（儿童成衣 /配饰）", "Brave Kid", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Diesel迪赛", "Diesel", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Jill Sander吉尔桑达", "Jill Sander", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Maison Margiela梅森马吉拉", "Maison Margiela", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Marni玛尼", "Marni", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Viktor & Rolf维果罗夫", "Viktor & Rolf", "OTB 集团", "OTB (Only The Brave)集团", "f"],
  ["Acne Studios", "", "其他品牌", "其他品牌", "f"],
  ["Ami阿米", "Ami", "其他品牌", "其他品牌", "f"],
  ["Ann Demeulemeester安迪穆拉米斯特", "Ann Demeulemeester", "其他品牌", "其他品牌", "f"],
  ["Alo Yoga", "", "其他品牌", "其他品牌", "f"],
  ["Brooks Brothers布克兄弟", "Brooks Brothers", "其他品牌", "其他品牌", "f"],
  ["Club Monaco摩纳哥会馆", "Club Monaco", "其他品牌", "其他品牌", "f"],
  ["Graff格拉夫", "Graff", "其他品牌", "其他品牌", "w"],
  ["Isabel Marant伊莎贝尔玛兰", "Isabel Marant", "其他品牌", "其他品牌", "f"],
  ["Lululemon露露乐蒙", "Lululemon", "其他品牌", "其他品牌", "f"],
  ["Moose Knuckles慕瑟纳可", "Moose Knuckles", "其他品牌", "其他品牌", "f"],
  ["Margaret Howell玛格丽特霍威尔", "Margaret Howell", "其他品牌", "其他品牌", "f"],
  ["Mikimoto御木本", "Mikimoto", "其他品牌", "其他品牌", "w"],
  ["Rick Owens瑞克欧文斯", "Rick Owens", "其他品牌", "其他品牌", "f"],
  ["Tasaki塔思琦", "Tasaki", "其他品牌", "其他品牌", "w"],
  ["Vivienne Westwood薇薇安韦斯特伍德（西太后）", "Vivienne Westwood", "其他品牌", "其他品牌", "f"],
  ["ANTA安踏", "ANTA", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["Arc'teryx始祖鸟", "Arc'teryx", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["DESCENTE迪桑特", "DESCENTE", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["FILA斐乐", "FILA", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["Jack Wolfskin狼爪", "Jack Wolfskin", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["KOLON SPORT可隆", "KOLON SPORT", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["Salomon萨洛蒙", "Salomon", "ANTA 安踏", "ANTA Sports安踏", "f"],
  ["Moschino莫斯奇诺", "Moschino", "Aeffe Group", "Aeffe Group", "f"],
  ["Burberry博柏利", "Burberry", "Burberry博柏利集团", "Burberry博柏利集团", "f"],
  ["Brunello Cucinelli 布内罗古奇拉利", "Brunello Cucinelli", "Brunello Cucinelli布内罗古奇拉利集团", "Brunello Cucinelli布内罗古奇拉利集团", "f"],
  ["Chanel香奈儿", "Chanel", "Chanel香奈儿集团", "Chanel香奈儿集团", "f"],
  ["Mackage迈凯奇", "Mackage", "Chelsey House俏时屋", "Chelsey House俏时屋", "f"],
  ["sporty&rich运动与富裕", "sporty&rich", "Chelsey House俏时屋", "Chelsey House俏时屋", "f"],
  ["r13", "", "Chelsey House俏时屋", "Chelsey House俏时屋", "f"],
  ["Zimmermann齐默尔曼", "Zimmermann", "Chelsey House俏时屋", "Chelsey House俏时屋", "f"],
  ["Michael Kors 迈克高仕", "Michael Kors", "Capri Holdings 卡普里集团", "Capri Holdings 卡普里集团", "f"],
  ["Jimmy Choo 周仰杰", "Jimmy Choo", "Capri Holdings 卡普里集团", "Capri Holdings 卡普里集团", "f"],
  ["Dolce&Gabbana 杜嘉班纳", "Dolce&Gabbana", "Dolce&Gabbana杜嘉班纳集团", "Dolce&Gabbana杜嘉班纳集团", "f"],
  ["Thom Browne 桑姆布朗尼", "Thom Browne", "Ermenegildo Zegna 杰尼亚集团", "Ermenegildo Zegna 杰尼亚集团", "f"],
  ["Zegna杰尼亚", "Zegna", "Ermenegildo Zegna 杰尼亚集团", "Ermenegildo Zegna 杰尼亚集团", "f"],
  ["Armani Exchange阿玛尼休闲", "Armani Exchange", "Giorgio Armani乔治阿玛尼集团", "Giorgio Armani乔治阿玛尼集团", "f"],
  ["Emporio Armani安普里奥阿玛尼", "Emporio Armani", "Giorgio Armani乔治阿玛尼集团", "Giorgio Armani乔治阿玛尼集团", "f"],
  ["Giorgio Armani乔治阿玛尼", "Giorgio Armani", "Giorgio Armani乔治阿玛尼集团", "Giorgio Armani乔治阿玛尼集团", "f"],
  ["Hermés爱马仕", "Hermés", "Hermés爱马仕集团", "Hermés爱马仕集团", "f"],
  ["Boss博斯", "Boss", "Hugo Boss 雨果博斯", "Hugo Boss雨果博斯集团", "f"],
  ["Hugo雨果", "Hugo", "Hugo Boss 雨果博斯", "Hugo Boss雨果博斯集团", "f"],
  ["Lanvin浪凡", "Lanvin", "Lanvin Group浪凡集团", "Lanvin Group浪凡集团", "f"],
  ["Sergio Rossi塞乔罗西", "Sergio Rossi", "Lanvin Group浪凡集团", "Lanvin Group浪凡集团", "f"],
  ["Max Mara Studio", "", "Max Mara麦丝玛拉集团", "Max Mara麦丝玛拉集团", "f"],
  ["Max & Co", "", "Max Mara麦丝玛拉集团", "Max Mara麦丝玛拉集团", "f"],
  ["S Max Mara", "", "Max Mara麦丝玛拉集团", "Max Mara麦丝玛拉集团", "f"],
  ["SportMax", "", "Max Mara麦丝玛拉集团", "Max Mara麦丝玛拉集团", "f"],
  ["Weekend Max Mara", "", "Max Mara麦丝玛拉集团", "Max Mara麦丝玛拉集团", "f"],
  ["Moncler盟可睐", "Moncler", "Moncler 盟可睐", "Moncler盟可睐集团", "f"],
  ["Stone Island石头岛", "Stone Island", "Moncler 盟可睐", "Moncler盟可睐集团", "f"],
  ["Church's", "", "Prada Group 普拉达", "Prada Group普拉达集团", "f"],
  ["Car Shoe", "", "Prada Group 普拉达", "Prada Group普拉达集团", "f"],
  ["Miu Miu缪缪", "Miu Miu", "Prada Group 普拉达", "Prada Group普拉达集团", "f"],
  ["Prada普拉达", "Prada", "Prada Group 普拉达", "Prada Group普拉达集团", "f"],
  ["Versace范思哲", "Versace", "Prada Group 普拉达", "Prada Group普拉达集团", "f"],
  ["Byredo柏芮朵", "Byredo", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Christian Louboutin Beauty路铂廷", "Christian Louboutin Beauty", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Charlotte Tilbury夏洛特蒂铂丽", "Charlotte Tilbury", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Dries Van Noten德赖斯范诺顿", "Dries Van Noten", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["L'Artisan Parfumeur阿蒂仙之香", "L'Artisan Parfumeur", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Penhaligon's潘海利根", "Penhaligon's", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Uriage依泉", "Uriage", "Puig 普伊格", "Puig普伊格集团", "c"],
  ["Rolex劳力士", "Rolex", "Rolex 劳力士", "Rolex劳力士集团", "w"],
  ["Tudor帝舵", "Tudor", "Rolex 劳力士", "Rolex劳力士集团", "w"],
  ["Coach蔻驰", "Coach", "Tapestry 泰佩思琦", "Tapestry泰佩思琦集团", "f"],
  ["Kate Spade凯特丝蓓", "Kate Spade", "Tapestry 泰佩思琦", "Tapestry泰佩思琦集团", "f"],
  ["Stuart Weitzman思缇韦曼", "Stuart Weitzman", "Tapestry 泰佩思琦", "Tapestry泰佩思琦集团", "f"],
  ["Salvatore Ferragamo菲拉格慕", "Salvatore Ferragamo", "Salvatore Ferragamo 菲拉格慕", "Salvatore Ferragamo菲拉格慕集团", "f"],
  ["Fay斐", "Fay", "TOD'S 托德斯", "TOD'S托德斯集团", "f"],
  ["Hogan霍根", "Hogan", "TOD'S 托德斯", "TOD'S托德斯集团", "f"],
  ["Roger Vivier罗杰维威耶", "Roger Vivier", "TOD'S 托德斯", "TOD'S托德斯集团", "f"],
  ["TOD'S托德斯", "TOD'S", "TOD'S 托德斯", "TOD'S托德斯集团", "f"],
  ["Giovanni Valentino 卓凡尼华伦天奴", "Giovanni Valentino", "Valentino 华伦天奴", "Valentino 华伦天奴集团", "f"],
  ["Valentino 华伦天奴", "Valentino", "Valentino 华伦天奴", "Valentino 华伦天奴集团", "f"],
  ["Sephora丝芙兰", "Sephora", "LVMH 路威酩轩", "LVMH路威酩轩集团", "o"],
];

// 统计